MKHOWTO = ~/projects/python24/Doc/tools/mkhowto

all:
	$(MKHOWTO) --all mailman-admin.tex
	$(MKHOWTO) --all mailman-install.tex
	$(MKHOWTO) --all mailman-member-es.tex
	$(MKHOWTO) --all mailman-member.tex
